const BASIC_TAB_INDEX = 0;
const DOCUMENT_INDEX = 1;
const INBOUND_INDEX = 2;
const ORIGINAL_OWNER_TAB_INDEX = 3;
const INSURANCE_INDEX = 4;
const NEW_OWNER_TAB_INDEX = 5;
const PAYMENT_TAB_INDEX = 6;
const RECEIPT_TAB_INDEX = 7;
